#CI nivel 01 - disparo manual através de clique 

#declaração do nome da pipeline
name: 'Execução Manual'

#gatilho ou triggers - regras de disparos
#gatilho manual = workflow_dispatch

on:
  workflow_dispatch: 

#tarefas a serem executadas na pipeline - jobs
jobs:

#nome do job
    e2e-tests:
    #maquina onde o job vai rodar
    runs-on: ubuntu-latest
        

     steps: 
          #clone do projeto
          - uses: actions/checkout@v4

          #passo a passo do node 
          - uses: actions/setup-node@v4
            with:
             node-version: 24.x

          #instalação do yarn 
          - name: instalando Yarn 
            run: npm install -g yarn 


          #instalação das dependencias 
          - name: instalando dependencias
            run: yarn

          # instalação o browser do Playwright 
          - name: instalando o browser do Playwright 
            run: yarn playwright install

          # execução dos testes e2e 
          - name: Executando testes e2e 
            run: yarn run e2e






